# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SVDS <- function(X) {
    X=as(X, "TsparseMatrix")
    .Call('PROJECTOR_SVDS', PACKAGE = 'PROJECTOR', X)
}


